### PR TITLE
Feature/libaspace 92

### PR DESCRIPTION
**Pull request by cfitz**
Version bump for aspace

### CODE REVIEW

**Comment by peichman-umd** [comment]
@cfitz I am trying to start up the Vagrant on my workstation, but the archivesspace application is failing to come up. The `/apps/aspace/archivesspace/logs/archivesspace.out` contains errors like the following:

```
Internal Server Error (500)

Request Method: GET
Request URL: http://aspacelocal:8083/config/enumerations

Database connection failed
	from /apps/aspace/archivesspace/data/tmp/jetty-0.0.0.0-8083-backend.war-_-any-/webapp/WEB-INF/app/main.rb:101:in `block in ArchivesSpaceService'
	from /apps/aspace/archivesspace/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1411:in `configure'
	from /apps/aspace/archivesspace/data/tmp/jetty-0.0.0.0-8083-backend.war-_-any-/webapp/WEB-INF/app/main.rb:78:in `<class:ArchivesSpaceService>'
	from /apps/aspace/archivesspace/data/tmp/jetty-0.0.0.0-8083-backend.war-_-any-/webapp/WEB-INF/app/main.rb:38:in `<main>'
	from org/jruby/RubyKernel.java:961:in `require'
	from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /apps/aspace/archivesspace/data/tmp/jetty-0.0.0.0-8083-backend.war-_-any-/webapp/WEB-INF/config.ru:1:in `block in (root)'
	from org/jruby/RubyBasicObject.java:1687:in `instance_eval'
	from /apps/aspace/archivesspace/data/tmp/jetty-0.0.0.0-8083-backend.war-_-any-/webapp/WEB-INF/config.ru:4:in `(root)'
	from uri:classloader:/vendor/rack-1.5.5/rack/builder.rb:55:in `<main>'
	from launcher/launcher.rb:92:in `start_server'
	from launcher/launcher.rb:157:in `main'
	from launcher/launcher.rb:261:in `<main>'
```

Is there any additional setup beyond what is listed in the README, or particular versions of the archivesspace-core or aspace-env that I need to use?

**Comment by cfitz** [comment]
@peichman-umd hm, i'm not the best at troubleshooting these vagrant issues, but it looks like it's not connecting to MySQL. Is mysql running and have the archivesspace db created in it? What happens if you try and just run archivesspace.sh ?  There should be some error message that's spit out when it tries to connect to the db.

**Comment by peichman-umd** [comment]
The database is running; I can connect t it using `mysql -u as -p archivesspace`. When I try starting the app by just running `archivesspace.sh`, I get this error:

```
E, [2017-11-13T19:12:22.849470 #7162] ERROR -- : Thread-2000:
=======================================================================
UNSUPPORTED DATABASE
=======================================================================

The database listed in your configuration:



is not officially supported by ArchivesSpace.
```

That makes me think there is some configuration missing somewhere.

**Comment by peichman-umd** [comment]
I just realized that I needed to source `/apps/aspace/config/env` before running `archivesspace.sh`, so it sould pick up environment variables. Even if I do that, though, and it says it started up okay, I am still getting an error when I try to go to https://aspacelocal/.

**Comment by cfitz** [comment]
There's odd. are you getting something that says:

```
 Connecting to database: jdbc:mysql://localhost:3306/archivesspace?user=[REDACTED]&password=[REDACTED]&useUnicode=true&characterEncoding=UTF-8. Max connections: 28
I, [2017-11-13T19:20:05.930955 #5833]  INFO -- : Thread-2000: All tables checked and confirmed set to UTF-8.  Nice job!
```

It might be your db_url is mangled

**Comment by peichman-umd** [comment]
The connection to the DB in the log output shows up as: `Connecting to database: jdbc:mysql://localhost:3306/archivesspace?user=[REDACTED]&password=[REDACTED]&useUnicode=true&characterEncoding=UTF-8. Max connections: 28`

**Comment by peichman-umd** [comment]
It looks like the root problem may be a gem version conflict:

```
Bundler::VersionConflict: Bundler could not find compatible versions for gem "rack":
  In snapshot (Gemfile.lock):
    rack (= 2.0.1)

  In Gemfile:
    mizuno (= 0.6.11) java was resolved to 0.6.11, which depends on
      rack (>= 1.0.0) java

    omniauth (~> 1.2.0) java was resolved to 1.2.2, which depends on
      rack (~> 1.0) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

            start at /apps/aspace/archivesspace/gems/gems/bundler-1.12.5/lib/bundler/resolver.rb:204
          resolve at /apps/aspace/archivesspace/gems/gems/bundler-1.12.5/lib/bundler/resolver.rb:184
          resolve at /apps/aspace/archivesspace/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:200
            specs at /apps/aspace/archivesspace/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:140
        specs_for at /apps/aspace/archivesspace/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:185
  requested_specs at /apps/aspace/archivesspace/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:174
  requested_specs at /apps/aspace/archivesspace/gems/gems/bundler-1.12.5/lib/bundler/environment.rb:19
            setup at /apps/aspace/archivesspace/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:14
            setup at /apps/aspace/archivesspace/gems/gems/bundler-1.12.5/lib/bundler.rb:95
           <main> at /apps/aspace/archivesspace/gems/gems/bundler-1.12.5/lib/bundler/setup.rb:19
          require at org/jruby/RubyKernel.java:961
           (root) at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
           <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:133
          require at org/jruby/RubyKernel.java:961
           (root) at /apps/aspace/archivesspace/data/tmp/jetty-0.0.0.0-8080-frontend.war-_-any-/webapp/WEB-INF/config/boot.rb:10
           (root) at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
          require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
           <main> at uri:classloader:/jruby/rack/rails/environment3.rb:23
     start_server at launcher/launcher.rb:92
             main at launcher/launcher.rb:168
           <main> at launcher/launcher.rb:254
```

**Comment by peichman-umd** [comment]
I was able to get the Vagrant to come up by going back to the LIBASPACE-82/PR #10. I will start by merging that PR, then continue on.

**Comment by cfitz** [comment]
@peichman-umd  I was able to get vagrant to start ( there was an issue with the solr image ). And things seem to run fine on the https://github.com/umd-lib/aspace-vagrant/pull/12 branch. Probably should skip this PR and just do that one ( which also includes these commits )

**Pull request merged**
